### ISSUE TITLE
MVP TO-DO LIST

### ISSUE THREAD

**Issue by Al-Andrew** [FadeTeam/Gmtk-2022#3]
## Player movement
 - [ ] Nicer values for the blue die
 - [x] Coyote time
 - [x] No more sliding 
 - [ ] Player facing <- adica sa tinem cont de in ce directie se uita si sa indreptam caracterul in directia asta, ar trebuii un sprite care sa nu fie asa simetric :D

## Weapons
 - [x] Wielding
 - [x] Switching
 - [x] Melee Weapons
 - [ ] Ranged Weapons
 - [x] Attacking

## Enemies
 - [ ] Base enemy 
 - [ ] 'De-engage` <- poti sa schimbi din rosu in albastru doar dupa ce ai omorat un mostru
 - [ ] Dummy enemy <- ca sa avem ce plasa in nivel

## Env
 - [ ] Camera movement
 - [ ] Un nivel mai lung de test
 - [ ] 'Engage' zone <- poti sa schimbi din albastru in rosu doar daca esti in engage zone
